Hw docker
GradientAspen/spring-boot-project pull request #13
Opened 2024-03-04 10:53 UTC by GradientAspen

2024-03-04 10:55 UTC, GradientAspen commented
I have a problem connecting to the debugger. During startup, the error "Unable to open debugger port (localhost:8000): java.io.IOException "handshake failed - connection prematurally closed""

2024-03-04 14:16 UTC, okuzan requested changes

2024-03-04 14:16 UTC, okuzan commented on src/main/java/com/project/springbootproject/repository/cartitem/CartItemRepository.java
>      void deleteCartItemsFromDb(Long id);
if you used annotations correctly, it should be done automatically

2024-03-04 14:16 UTC, okuzan commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/bookDb?serverTimeZone=UTC
always remove commented out code

2024-03-04 14:16 UTC, okuzan commented on docker-compose.yml
> +    environment:
incomplete configuration

2024-03-05 10:33 UTC, okuzan requested changes

2024-03-05 10:33 UTC, okuzan commented on src/main/java/com/project/springbootproject/repository/cartitem/CartItemRepository.java
>      void deleteCartItemsFromDb(Long id);
not fixed

2024-03-05 10:48 UTC, GradientAspen commented on src/main/java/com/project/springbootproject/repository/cartitem/CartItemRepository.java
>      void deleteCartItemsFromDb(Long id);
An error occurs when using the method without annotation 2024-03-05T12:41:35.951+02:00 ERROR 22868 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Request processing failed: org.springframework.dao.InvalidDataAccessApiUsageException: Expecting a SELECT query : `UPDATE CartItem ci SET ci.isDeleted = true WHERE ci.shoppingCart.id = :id`] with root cause

org.hibernate.query.IllegalSelectQueryException: Expecting a SELECT Query [org.hibernate.query.sqm.tree.select.SqmSelectStatement], but found org.hibernate.query.sqm.tree.update.SqmUpdateStatement [UPDATE CartItem ci SET ci.isDeleted = true WHERE ci.shoppingCart.id = :id]
	at org.hibernate.query.sqm.internal.SqmUtil.verifyIsSelectStatement(SqmUtil.java:93) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.verifySelect(QuerySqmImpl.java:489) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:498) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:427) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.hibernate.query.spi.AbstractSelectionQuery.getSingleResult(AbstractSelectionQuery.java:559) ~[hibernate-core-6.3.1.Final.jar:6.3.1.Final]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:223) ~[spring-data-jpa-3.2.0.jar:3.2.0]

2024-03-05 11:59 UTC, okuzan approved these changes

2024-03-05 12:04 UTC, merged